# Lab ARGOS: 1 Windows victim, 1 Linux victim + Postgres, 1 Linux manager.
# Red interna 192.168.56.0/24
Vagrant.configure("2") do |config|
  config.vm.define "lab-manager" do |m|
    m.vm.box      = "bento/ubuntu-22.04"
    m.vm.hostname = "lab-manager"
    m.vm.network "private_network", ip: "192.168.56.10"
    m.vm.synced_folder ".", "/vagrant"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus   = 2
    end
    m.vm.provision "shell", path: "provision/manager.sh"
  end
  config.vm.define "linux-victim" do |l|
    l.vm.box      = "bento/ubuntu-22.04"
    l.vm.hostname = "linux-victim"
    l.vm.network "private_network", ip: "192.168.56.21"
    l.vm.synced_folder ".", "/vagrant"
    l.vm.provider "virtualbox" do |vb|
      vb.memory = 3072
      vb.cpus   = 2
    end
    l.vm.provision "shell", path: "provision/linux_victim.sh"
  end
  config.vm.define "windows-victim" do |w|
    w.vm.box      = "gusztavvargadr/windows-10"
    w.vm.hostname = "win-victim"
    w.vm.network "private_network", ip: "192.168.56.20"
    w.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus   = 2
    end
    w.vm.provision "shell", path: "provision/windows_victim.ps1"
  end
end